{% set name = "caio" %}
{% set version = "0.9.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caio-{{ version }}.tar.gz
  sha256: 70c9556dc003df1e3ea8dca5cc32ef0bb9213cfbc5a2b80003ba37018689326f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - caio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mosquito/caio
  summary: Asynchronous file IO for Linux Posix and Windows.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
