{% set name = "caio" %}
{% set version = "0.9.25" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16498e7f81d1d0f5a4c0ad3f2540e65fe25691376e0a5bd367f558067113ed10

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - pip
    - python
    - setuptools >=77
  run:
    - python

# missing 'aiomisc' required for project tests
test:
  imports:
    - caio
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip

about:
  home: https://github.com/mosquito/caio
  summary: Asynchronous file IO for Linux Posix and Windows.
  description: Python bindings for Linux AIO API and simple asyncio wrapper.
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  dev_url: https://github.com/mosquito/caio
  doc_url: https://github.com/mosquito/caio

extra:
  recipe-maintainers:
    - thewchan
